### ISSUE TITLE
Problems with docker.

### ISSUE THREAD

**Issue by AVS-Verba** [PacktPublishing/Hands-on-Machine-learning-with-C-Second-Edition#1]
Hi!
I was interested in your book, for which I am very grateful.
Started building your examples using docker.
I ran into some problems.
1. Wget should be moved higher, because then cmake is not loaded
2. In this line, it should rather be like this - RUN pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu
3. This line should rather say RUN pip install mlflow==2.15.0

However, I still couldn't build the container. On mac & ubuntu there is one and the same error.
I will be grateful if you help in solving this error.

[LogsDocker.txt](https://github.com/user-attachments/files/16917126/LogsDocker.txt)

**Comment by Kolkir** [comment]
Hi, thanks for reporting. Did you see the error in your log:
```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by Kolkir** [comment]
I've fixed scripts
